[project]
authors = [
  { name = "A.suzuki", email = "suzu.devworks@gmail.com" },
]
dependencies = []
description = "Add your description here"
name = "examples-workspace-cli"
readme = "README.md"
requires-python = ">=3.12"
version = "0.1.0"

[project.scripts]
examples-workspace-cli = "examples_workspace_cli:main"

[build-system]
build-backend = "hatchling.build"
requires = ["hatchling"]
